name: Release Automation

# Controls when the action will run. 
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Generate CHANGLOG compared to previous release, based on a template file and a list of commit type prefixes
      - name: PSBuild
        run: |
          .\Build_Full_CheckScript.ps1
                
      - name: Upload Output Script to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Full_Check_Script.sql
          tag: ${{ github.ref }}
          overwrite: true
